### ISSUE TITLE
[LEAP] Dask workers limit

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#1293]
Reported in https://2i2c.freshdesk.com/a/tickets/139:

### Scenario

Two different hub users ran the following code more or less at the same time

```
from dask_gateway import Gateway
g = Gateway()
options = g.cluster_options()
options.worker_cores = 1
options.worker_memory = 10
gc = g.new_cluster(cluster_options=options)
nworkers = 20
gc.scale(nworkers)
```

### What happened

- One of the users was able to get to 10 workers or so
- But the other is not able to scale at all

#### Logs

Looking at the `dask-gateway` controller logs, the error below seemed relevant

```
Cluster scaled to 100 - creating 89 workers, deleting 0 stopped workers
Failed to create pod in namespace prod - Operation cannot be fulfilled on resourcequotas "gke-resource-quotas": the object has been modified; please apply your changes to the latest version and try again
```

### Debug

Running ` kubectl get resourcequota gke-resource-quotas -o yaml -n prod` returned:

```
status:
  hard:
    count/ingresses.extensions: 100k
    count/ingresses.networking.k8s.io: 100k
    count/jobs.batch: 50k
    pods: 15k
    services: 5k
  used:
    count/ingresses.extensions: "1"
    count/ingresses.networking.k8s.io: "1"
    count/jobs.batch: "0"
    pods: "7"
    services: "6"
```

#### Code refs

LEAP cluster resources set through terraform: https://github.com/2i2c-org/infrastructure/blob/master/terraform/gcp/projects/leap.tfvars

### Problem
Is this a limits problem or is it something else?
