### ISSUE TITLE
Figure out authentication for hub services proxied from the outside

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/infrastructure#171]
From @consideration:

---

I've not explored this yet, but is my understanding correct that JupyterHub can act as an OAuth2 provider?

Looking at [jupyterhub's documentation about HubOAuth](https://jupyterhub.readthedocs.io/en/stable/api/services.auth.html) I'm not confident. How to generate a client_secret / client_id? How does the JupyterHub service's api-token relate to all of this if it does in any way?

I have used a oauth2-proxy deployment + nginx-ingress controller with some annotations to do some magic in the past.

```yaml
   # An Ingress resource's annotation of a documentation
   # webserver that I wanted to protect with OAuth2 based authentication

    # auth-url / auth-signing:
    #   ref: https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    # configuration-snippet:
    #   To ensure /docs redirect to /docs/ which help the browser evaluate
    #   relative paths links to /docs/something instead of /something.
    #
    #   ref: https://github.com/kubernetes/ingress-nginx/issues/646#issue-224161025
    nginx.ingress.kubernetes.io/configuration-snippet: rewrite ^(/docs)$ $1/ permanent;
    # Disabled configuration:
    #   Using nginx-ingress-controller to modify the path beforing proxying it
    #   doesn't work so well it seems. It does as it should when we declare the
    #   path as /docs but not as /docs(/|$)(.*) which would be required for
    #   version 0.22.0+ and we currently are at 0.21.0. To ensure stability, I
    #   opt to let the actual webserver handle this in its nginx configuration
    #   instead with a rewrite directive.
    #
    # # rewrite-target:
    # #   ref: https://kubernetes.github.io/ingress-nginx/examples/rewrite/#examples
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    #
```

## References
- https://oauth2-proxy.github.io/oauth2-proxy/
- https://github.com/oauth2-proxy/oauth2-proxy
- https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/

_Originally posted by @consideRatio in https://github.com/2i2c-org/pilot-hubs/issues/163#issuecomment-762323707_
