### ISSUE TITLE
Update our hub-health service to properly set roles

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#1974]
### Context

Warning in the JupyterHub logs:

```
[W 2022-12-05 10:49:52.801 JupyterHub app:2312] Service hub-health sets `admin: True`, which is deprecated in JupyterHub 2.0. You can assign now assign roles via `JupyterHub.load_roles` configuration. If you specify services in the admin role configuration, the Service admin flag will be ignored.
```

We should update our helm chart accordingly.

**Comment by sgibson91** [comment]
Needs investigation to see if this is still the case or if it has resolved itself

**Comment by consideRatio** [comment]
The permissions for the health check should still should be narrowed to the relevant permissions only:

https://github.com/2i2c-org/infrastructure/blob/864d8f8a34383805ff4ab6241a50afc3fc83803e/helm-charts/basehub/values.yaml#L517-L527

## Action points

- Identify required [JupyterHub RBAC permissions](https://jupyterhub.readthedocs.io/en/stable/rbac/scopes.html)
- Declare an entry for `hub.loadRoles` with the permissions (scopes) in basehub, applying it to the `hub-health` jupyterhub service.
  ```yaml
  jupyterhub:
    hub:
      loadRoles:
        hub-health:
          # scopes should at least include permissions to start the
          # user server for the user "deployment-service-check"
          scopes: [???]
          services: [hub-health]
  ```

Btw a bug to be aware about is that changes to `hub.loadRoles` doesn't yet trigger a restart of the hub pod as it should, see https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3251.
