### ISSUE TITLE
Force user pods to schedule on user nodes (not next to hub pod etc)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2163]
I think [`scheduling.userPods.nodeAffinity.matchNodePurpose=require`](https://z2jh.jupyter.org/en/stable/resources/reference.html#scheduling-userpods-nodeaffinity-matchnodepurpose) is a jupyterhub configuration we should go for by default. It makes user pods get a required nodeAffinity (like `nodeSelector` but separate) forcing them to schedule on user nodes so they can't end up at core nodes - as they can now.

```yaml
  jupyterhub:
    scheduling:
      userPods:
        nodeAffinity:
          matchNodePurpose: require
```

That they tolerate the tainted user nodes makes them prefer scheduling there, but they can schedule on the core node pool as well without this if there is no space on an already available user node.

If this is enabled, and we don't have the proper taints on the user nodes - we will break things. But this should be caught by our health check that tests start a user pod!
