### ISSUE TITLE
grafana: tighten grafana charts k8s RBAC permissions (ClusterRole -> Role)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2182]
I saw that Grafana is creating a PodSecurityPolicy, which is something that is being deprecated and removed from k8s and we get warnings about it.

Looking into that further, I see that `grafana` chart is granted a ClusterRole to read configmaps and secrets, which I suspect may be more permissions than is relevant for grafana to have - at least i suspect so when its in the same k8s namespace as prometheus.

With that in mind, I'd like to try tighten the permissions. This means that if the grafana software would be compromised for example, they can't read k8s Secrets in other namespaces etc.

### Action point

- Trial setting `rbac.namespaced=true` and `rbac.pspEnabled=false`

### Related

- Default values include [`rbac.namespaced=false` and `rbac.pspEnabled=true`](https://github.com/grafana/helm-charts/blob/b81425edb150818c13df6790ae8021d92f8163eb/charts/grafana/values.yaml#L16-L22)
- [Role](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/role.yaml) and [ClusterRole](https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/clusterrole.yaml) resources.

**Comment by consideRatio** [comment]
The ClusterRole created for our grafana isn't containing any rules, so why not declare `rbac.namespaced=true` and avoid making someone consider reviewing such unexpected permissions grant again.

I think it should be fine to adjust these default values.

The PSP enforces this currently:

```
support-grafana         false          RunAsAny   RunAsAny    MustRunAs   MustRunAs   false            configMap,emptyDir,projected,csi,secret,downwardAPI,persistentVolumeClaim
```

```
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - csi
  - secret
  - downwardAPI
  - persistentVolumeClaim
```
