### ISSUE TITLE
GKE clusters get two core nodes without being CPU / Memory constrained

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2199]
It seems that at least some GKE clusters, like `linked-earth` gets two core nodes instead of one, which is a waste of cloud resources I think. I think it is because the cluster-autoscaler scales up for `konnectivity-agent` so that it can have three pods in a 2+1 configuration instead of having all on the same node.

This isn't suitable for us, and I'm not sure how we ought to avoid it. I think we can do `kubectl edit` on resources like the `Deployment` of konnectivity-agent, or influence the konnectivity-agent-autoscaler that runs `gke.gcr.io/cluster-proportional-autoscaler`. But, how to make this change so that its not reverted by GKE at a later point in time or similar?

The problem stems from use of a cluster-proportional-autoscaler that adds one pod per node, but then the konnectivity-agent pod's don't tolerate the user nodes and stack up on core nodes. In a situation with two core nodes and one user node, we have 3+1 konnectivity-agent's running on the core nodes currently.

```yaml
kind: Deployment
metadata:
  annotations:
    components.gke.io/layer: addon
    credential-normal-mode: "true"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: konnectivity-agent
  name: konnectivity-agent
  namespace: kube-system
spec:
  replicas: 3
```

```yaml
  # konnectivity-agent's pod spec includes this
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        k8s-app: konnectivity-agent
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
  - labelSelector:
      matchLabels:
        k8s-app: konnectivity-agent
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
```

### Related

- About [`topologySpreadConstraints`](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/)
- [k8s official Konnectivity service](https://kubernetes.io/docs/concepts/architecture/control-plane-node-communication/#konnectivity-service)
