### ISSUE TITLE
ingress-controller pod that routes all incoming traffic to k8d pods got evicted?

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2322]
Julius at LEAP reported seeing a popup associated with loosing connection between JupyterLab in the browser and the jupyter server in https://2i2c.freshdesk.com/a/tickets/528.

The popup [stems from jupyterlab beliving the connection is lost to the user server](https://github.com/jupyterlab/jupyterlab/blob/4dd9e9e9b8d52ffff5b369a2c491084416e1f598/packages/hub-extension/src/index.ts#L118-L186). I don't think this relates to Julius internet connection, but a disruption of networking for some reason.

1. Was it the jupyterhub chart's proxy pod being evicted/restarted? No.
2. Was it the ingress controller pod being evicted/restarted? Yes, it was evicted I think!

Why was the ingress controller pod evicted and a new pod started? I'm quite sure it was evicted from a node because memory pressure, because I see a node-exporter daemonset pod that can't be evicted restarted because it was OOMKilled just a minute before a new ingress controller pod was started on another node.

We can avoid this by having better memory requests for the ingress proxy pod, and by having multiple replicas of the ingress controller pods. Having these highly available and reliably running is very relevant.

### Related

Our `ingress-nginx` chart configuration doesn't specify any cpu or memory requests.

https://github.com/2i2c-org/infrastructure/blob/26691bfc94315dc86e189e7c141b90a3990d850b/helm-charts/support/values.yaml#L17-L36

The [default values for `ingress-nginx` are these](https://github.com/kubernetes/ingress-nginx/blob/ec2fe2b6d1e99202d15b6c0577bcfd69cf461c3a/charts/ingress-nginx/values.yaml#L316-L326):

```yaml
    ## Define requests resources to avoid probe issues due to CPU utilization in busy nodes
    ## ref: https://github.com/kubernetes/ingress-nginx/issues/4735#issuecomment-551204903
    ## Ideally, there should be no limits.
    ## https://engineering.indeedblog.com/blog/2019/12/cpu-throttling-regression-fix/
    resources:
        ##  limits:
        ##    cpu: 100m
        ##    memory: 90Mi
        requests:
            cpu: 100m
            memory: 90Mi
```

- #2222
- #2228 
- #2127

### Action points

- [x] Estimate memory use of ingress controller pods
- [x] Increase the default memory request of 90Mi
  - #2324
