### ISSUE TITLE
[nasa-cryo] Investigate IRSA IAM configuration to support notebooks using S3 clients to access external dataset buckets with requester pays

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2483]
### Context

Ref: https://2i2c.freshdesk.com/a/tickets/628
Link: CryoInTheCloud/hub-image#52

When using s3 datasets the community users get errors when trying to use requester pays.

The community is using datasets via gdal vsis3 bucket urls. See below. 

```python
import boto3
import os
from osgeo import gdal
gdal.GetActualURL('/vsis3/usgs-landsat/collection02/level-1/standard/oli-tirs/2019/008/113/LC08_L1GT_008113_20190507_20200829_02_T2/LC08_L1GT_008113_20190507_20200829_02_T2_B2.TIF')
'https://usgs-landsat.s3.amazonaws.com/collection02/level-1/standard/oli-tirs/2019/008/113/LC08_L1GT_008113_20190507_20200829_02_T2/LC08_L1GT_008113_20190507_20200829_02_T2_B2.TIF'
```

**Comment by pnasrat** [comment]
Related docs 

- https://github.com/OSGeo/gdal/issues/4058
- https://gdal.org/user/virtual_file_systems.html#vsis3-aws-s3-files
- https://repost.aws/knowledge-center/eks-restrict-s3-bucket

**Comment by pnasrat** [comment]
Note prior issue  https://github.com/CryoInTheCloud/hub-image/issues/35 has gdal>=3.6 

```
conda list | grep gdal
gdal                      3.6.2           py310hc1b7723_3    conda-forge
libgdal                   3.6.2                h10cbb15_3    conda-forge
```

**Comment by pnasrat** [comment]
https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/roles/details/nasa-cryo-prod?section=permissions

```
{
    "Statement": [
        {
            "Action": [
                "s3:*"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::usgs-landsat"
            ]
        },
        {
            "Action": [
                "s3:*"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::usgs-landsat/*"
            ]
        }
    ],
    "Version": "2012-10-17"
}
```

**Comment by pnasrat** [comment]
See also #1979

**Comment by pnasrat** [comment]
1. I setup an aws-cli pod running in prod with some env from a notebook pod
2. `kubectl apply -f aws-cli.yaml`

```
kubectl exec -n prod -it aws-cli -- aws s3 ls s3://usgs-landsat/collection02/level-1/standard/oli-tirs/2019/008/113/LC08_L1GT_008113_20190507_20200829_02_T2/LC08_L1GT_008113_20190507_20200829_02_T2_B2.TIF 

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
command terminated with exit code 254
```

vs

```
kubectl exec -n prod -it aws-cli -- aws s3 ls s3://usgs-landsat/collection02/level-1/standard/oli-tirs/2019/008/113/LC08_L1GT_008113_20190507_20200829_02_T2/LC08_L1GT_008113_20190507_20200829_02_T2_B2.TIF --request-payer requester
2020-08-29 01:58:40   38910987 LC08_L1GT_008113_20190507_20200829_02_T2_B2.TIF

```


```yaml
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: prod
spec:
  serviceAccount: user-sa
  serviceAccountName: user-sa
  containers:
  - name: aws-cli
    env:
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
    - name: AWS_DEFAULT_REGION
      value: us-west-2
    - name: AWS_REGION
      value: us-west-2
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::REDACTED:role/nasa-cryo-prod
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    image: amazon/aws-cli:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
        name: aws-iam-token
        readOnly: true
  restartPolicy: Always
```
