### ISSUE TITLE
utoronto nbgitpuller in rstudio tries to pull to /home/jovyan which is ro

### ISSUE THREAD

**Issue by pnasrat** [2i2c-org/infrastructure#2559]
Ref: https://2i2c.freshdesk.com/a/tickets/726

nbgitpuller doesn’t seem to be working on https://r.datatools.utoronto.ca

For example trying to pull https://github.com/ntaback/learnr_test2 into the hub with 

https://r.datatools.utoronto.ca/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fntaback%2Flearnr_test2&urlpath=rstudio%2F&branch=main

Throws the error … 

```
rstudio@jupyter-pris-2enasrat-40utoronto-2eca:~$ pwd
/home/rstudio
rstudio@jupyter-pris-2enasrat-40utoronto-2eca:~$ ls /home/jovyan/
shared
rstudio@jupyter-pris-2enasrat-40utoronto-2eca:~$ id
uid=1000(rstudio) gid=1000(rstudio) groups=1000(rstudio),50(staff),100(users)
rstudio@jupyter-pris-2enasrat-40utoronto-2eca:~$ cd /home/jovyan/
rstudio@jupyter-pris-2enasrat-40utoronto-2eca:/home/jovyan$ ls -al
total 9
drwxr-xr-x 3 root    root    4096 May 19 14:40 .
drwxr-xr-x 1 root    root    4096 May 19 14:40 ..
drwxr-xr-x 2 rstudio rstudio   64 Dec 13 04:51 shared
rstudio@jupyter-pris-2enasrat-40utoronto-2eca:/home/jovyan$ 
```

This can be worked around by forcing a [targetPath](https://nbgitpuller.readthedocs.io/en/latest/topic/url-options.html#targetpath) `https://r.datatools.utoronto.ca/user/pris.nasrat@utoronto.ca/git-pull?repo=https%3A%2F%2Fgithub.com%2Fntaback%2Flearnr_test2.git&urlpath=rstudio%2F&branch=main&redirects=1&targetPath=/home/rstudio/foo`

**Comment by pnasrat** [comment]
Possibly jupyterhub/nbgitpuller#268

**Comment by pnasrat** [comment]
```
jupyter serverextension list
config dir: /srv/conda/etc/jupyter
    jupyter_server_proxy  enabled 
    - Validating...
      jupyter_server_proxy  OK
    jupyter_resource_usage  enabled 
    - Validating...
      jupyter_resource_usage 0.7.1 OK
    jupyter_server_ydoc  enabled 
    - Validating...
      X is jupyter_server_ydoc importable?
    jupyterlab  enabled 
    - Validating...
      jupyterlab 3.6.3 OK
    nbgitpuller  enabled 
    - Validating...
      nbgitpuller 1.1.1 OK
    retrolab  enabled 
    - Validating...
      retrolab 0.3.21 OK
```

**Comment by pnasrat** [comment]
Hmm ok so cwd of PID 1 which is jupyterhub singleuser is /home/jovyan. So maybe we are not seetting notebook_dir or server_root_dir correctly here. 

```
ls -al /proc/1/cwd
lrwxrwxrwx 1 rstudio rstudio 0 May 19 15:19 /proc/1/cwd -> /home/jovyan
```

**Comment by pnasrat** [comment]
```yaml
    volumeMounts:
    - mountPath: /home/rstudio
      name: home
      subPath: pris-2enasrat-40utoronto-2eca
    - mountPath: /etc/gitconfig
      name: files
      subPath: gitconfig
    - mountPath: /etc/github/github-app-private-key.pem
      name: files
      subPath: github-app-private-key.pem
    - mountPath: /usr/local/etc/ipython/ipython_kernel_config.json
      name: files
      subPath: ipython_kernel_config.json
    - mountPath: /usr/local/etc/jupyter/jupyter_notebook_config.json
      name: files
      subPath: jupyter_notebook_config.json
    - mountPath: /usr/local/etc/jupyter/jupyter_server_config.json
      name: files
      subPath: jupyter_server_config.json
    - mountPath: /home/jovyan/shared
      name: home
      readOnly: true
      subPath: _shared
    workingDir: /home/jovyan
```
