### ISSUE TITLE
pangeo-hubs: recover prometheus-metrics

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2688]
As part of trying to get prometheus-server to start successfully with OOMKilled issues and inability to request even more memory without changing the k8s node type, I removed a `PV` and `PVC` resource in the pangeo-hubs k8s cluster. Doing so, we got provisioned a new persistent disk that became associated with the new PV.

The PV deleted was configured with `Retain` as a policy, which means that deleting the PV doesn't delete the actual disk associated with the PV.

As suggested by @yuvipanda in https://github.com/2i2c-org/infrastructure/issues/2366#issuecomment-1601152150, we want to remedy this deletion. We want to have a PVC and PV, where the PV references the previous disk, not the new. To do this though, we would need to know the ID of the previous disk etc, but I lack access to pangeo-hubs and can't do it.

**Comment by consideRatio** [comment]
I think maybe we got the same disk provisioned back to us, because prometheus-server fails to startup once again. Either we got the previous disk coupled to the new PV, or we got the new disk so populated with things over a short period of time that it fails to start again.

**Comment by yuvipanda** [comment]
Hopefully this is the old disk, and we can recover this data? I think prometheus data, especially for in use cluster, should be considered user data and preserved. We should be *extremely* careful about deleting it and not do that to the extent possible.

<img width="683" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/b97b256a-44d5-40fd-a7b8-070d6cfe9066">

@consideRatio it's definitely not the same disk. I don't know if the startup problems are related to the disk, but my intuiton is that they are not.

**Comment by yuvipanda** [comment]
I mounted this disk onto a pod with the following yaml:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  volumes:
  - name: volume
    gcePersistentDisk:
      pdName:  gke-pangeo-hubs-cluste-pvc-55aae527-9546-4cbc-8efc-df47046272ab 
      fsType: ext4
  containers:
    - name: shell
      image: ubuntu/nginx:latest
      volumeMounts:
        - mountPath: /data
          name: volume

```

Unfortunately, this is a leftover PVC from a long time ago (Aug 2021), and I think we have lost all metrics :(

```
root@test:/data# ls -la
total 36
drwxrwsr-x 5 root   nogroup  4096 Aug 23  2021 .
drwxr-xr-x 1 root   root     4096 Jun 24 00:51 ..
drwxr-sr-x 2 nobody nogroup  4096 Aug 23  2021 chunks_head
-rw-r--r-- 1 nobody nogroup     0 Aug 23  2021 lock
drwxrws--- 2 root   nogroup 16384 Aug 23  2021 lost+found
-rw-r--r-- 1 nobody nogroup 20001 Aug 23  2021 queries.active
drwxr-sr-x 2 nobody nogroup  4096 Aug 23  2021 wal

```
