### ISSUE TITLE
deployer generate-gcp-cluster: invalid support chart values for prometheusIngressAuthSecret

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2770]
I used `deployer generate-gcp-cluster` and ended up with a `enc-support.secret.values.yaml` file that looked invalid like below when decrypted:

```yaml
prometheusIngressAuthSecret:
    username: b''btw<asdfasdfasdfasdfxivvo3u?sB.}-uasdfasdfasdfYzlZOg"5)X<W;S
    #K)5q<'asdfasdfasdfqwb[DR3BasdfasdfasdfO(x[L]7,*JF#"5ekb7:]Y_]X.p%asdfasdfasdf*6aa3
    password: null
```
