### ISSUE TITLE
[Request deployment] New Hub -- Indian Ocean Hackweek 2023

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#2821]
### The GitHub handle of the community representative

eeholmes (EDIT: fixed typo)

### Hub important dates

- **Target Start Date:** 2023-08 -01 (likely not possible until a bit later given current work load)
- **Required Start Date:** 2023--08-08
- **Important dates for usage:** 2023-09-10 through 2023-09-22. This is when the Hackathon will take place. 

### Hub Authentication Type

GitHub (e.g., @mygithubhandle)

### First Hub Administrators

@eeholmes

### [GitHub Auth only] How would you like to manage your users?

Allowing members of a specific GitHub organization (EDIT: specific team, see below)

### [GitHub Teams Auth only] Profile restriction based on team membership

EDIT: https://github.com/orgs/Hackweek-ITCOocean/teams/itcoocean-hackweek-2023

### Hub logo image URL

EDIT: https://user-images.githubusercontent.com/2545978/253672085-ec5ca6fb-147b-4fcd-87f1-431108b62558.png

Looks like:
![](https://user-images.githubusercontent.com/2545978/253672085-ec5ca6fb-147b-4fcd-87f1-431108b62558.png)

### Hub logo website URL

https://incois.gov.in/ITCOocean/index.jsp

### Hub user image GitHub repository

pending

### Hub user image tag and name

pending

### Extra features you would like to enable

- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

AWS

### (Optional) Preferred cloud region

us-west-2 (shared 2i2c cluster: 2i2c-aws-us)

### (Optional) Billing and Cloud account

None

### Other relevant information to the features above

Research hub on a shared cluster (likely hosted in AWS us-west-2). Additional details are being gathered through async g-doc running notes with @eeholmes. Thanks in advance to @jmunroe for assistance with this while @colliand is away on vacation. 

This hub will run from early August through mid-October.

When filling in operated by, funded by, etc fields (https://github.com/2i2c-org/infrastructure/issues/2821#issuecomment-1636388679):

>"Openscapes" should be "ITCOocean" with link to https://incois.gov.in/ITCOocean/index.jsp
>
>Funded by: Should be "ITCOocean Hackweek Team" with no url (EDIT: Should be `ESIP` instead)

### Tasks to deploy the hub

- [x] 1. Deploy information filled in above
- [x] 2. Engineer who will deploy the hub is assigned
- [x] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [x] 4. Initial Hub deployment PR <link to PR>
- [x] 5. Administrators able to log on -> Hub now in steady-state

**Comment by eeholmes** [comment]
A few corrections

> ### The GitHub handle of the community representative
> eeholmes *was missing "s"*
> 
> ### Hub important dates
> * **Target Start Date:** 2023-08 -01 (likely not possible until a bit later given current work load)
> * **Required Start Date:** 2023--08-08
> * **Important dates for usage:** 2023-09-10 through 2023-09-22. This is when the Hackathon will take place.
> 
> ### Hub Authentication Type
> GitHub (e.g., @MyGitHubHandle)
> 
> ### First Hub Administrators
> @eeholmes

Not all GitHub organization members. I would like hub access restricted to this team on the organization
https://github.com/orgs/Hackweek-ITCOocean/teams/itcoocean-hackweek-2023

> ### [GitHub Auth only] How would you like to manage your users?
> ~~Allowing members of a specific GitHub organization~~ *Only members of the itcoocean-hackweek-2023 team*
> 
> ### [GitHub Teams Auth only] Profile restriction based on team membership
Yes, this team https://github.com/orgs/Hackweek-ITCOocean/teams/itcoocean-hackweek-2023

> 
> ### Hub logo image URL
![incois-logo](https://github.com/2i2c-org/infrastructure/assets/2545978/ec5ca6fb-147b-4fcd-87f1-431108b62558)

> 
> ### Hub logo website URL

https://incois.gov.in/ITCOocean/index.jsp
> 
> ### Hub user image GitHub repository
> pending
> 
> ### Hub user image tag and name
> pending
> 
> ### Extra features you would like to enable
> * [ ]  Dedicated Kubernetes cluster
> * [ ]  Scalable Dask Cluster
> 
> ### (Optional) Preferred cloud provider
> None
> 
> ### (Optional) Preferred cloud region
us-west-2
> 
> ### (Optional) Billing and Cloud account
> None
> 
> ### Other relevant information to the features above
> Research hub on a shared cluster (likely hosted in AWS us-west-2). Additional details are being gathered through async g-doc running notes with @eeholmes. Thanks in advance to @jmunroe for assistance with this while @colliand is away on vacation.
> 
> This hub will run from early August through mid-October.
> 
> ### Tasks to deploy the hub
> * [ ]  1. Deploy information filled in above
> * [ ]  2. Engineer who will deploy the hub is assigned
> * [ ]  3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
> * [ ]  4. Initial Hub deployment PR
> * [ ]  5. Administrators able to log on -> Hub now in steady-state

**Comment by eeholmes** [comment]
Re landing page for hub. If it will look similar to the Openscapes hub,

<img width="852" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/2545978/4e358c6c-e40c-4741-9715-030fafdb800e">

"Openscapes" should be "ITCOocean" with link to https://incois.gov.in/ITCOocean/index.jsp

Funded by: Should be "ITCOocean Hackweek Team" with no url

**Comment by colliand** [comment]
Thanks @eeholmes!

**Comment by eeholmes** [comment]
@colliand I am working on the hub image questions. I need to update our Python image and build our R image.

**Comment by eeholmes** [comment]
Hub user images

There are 4. Two for Python, Two for R
On DockerHub
* eeholmes/iopython:20230714 Name: Geospatial Python with tensorflow (default)
* openscapes/python:f577786 Name: Geospatial Python
* openscapes/rocker:a7596b5 Name: Geospatial R
*  eeholmes/iorocker:20230714 Name: Geospatial R with SDM

Note I think the Geospatial R with SDM has a problem as my kernel is not spinning up when I select that one. but I will fix that later.

Here is the current config file for our daskhub that my team is using during development of the course content. This is a bit of a hack but is mostly doing what we want, which is allowing users to pick different images.  Note the machine sizes are not how we want it so ignore that part. Something more like what Openscapes has or whatever you think is best. Currently we keep maxing out the memory when working with big data sets.

Regarding the extra storage. We have a 1 TB shared drive where we have the data and notebooks that the students will be using. It should be read only for the students but read/write for the admins.

Here are the content developers who will need to write to the shared drive:
https://github.com/orgs/Hackweek-ITCOocean/teams/hackweek-2023-team/members

```
jupyterhub:
  hub:
    config:
      GitHubOAuthenticator:
        client_id: xxxxx
        client_secret: xxxx
        oauth_callback_url: xxxx
        allowed_organizations:
          - nmfs-opensci:DaskHub
        scope:
          - read:org
      JupyterHub:
        authenticator_class: github
      KubeSpawner:
        working_dir: /home/jovyan
    allowNamedServers: true
    networkPolicy:
      enabled: false
    readinessProbe:
      enabled: false
  proxy:
    https:
      enabled: true
      hosts:
        - dhub.opensci.live
      letsencrypt:
        contactEmail: eli.holmes@noaa.gov        
  singleuser:
    defaultUrl: /lab
    # Defines the default image
    storage:
      capacity: 100Gi
      extraVolumes:
        - name: jupyterhub-shared
          persistentVolumeClaim:
            claimName: daskhub-pvc
      extraVolumeMounts:
        - name: jupyterhub-shared
          mountPath: /home/jovyan/shared
    image:
      name: openscapes/python
      tag: f577786
    profileList:
      - display_name: "4 CPU / 32 GB RAM"
        description: &profile_list_description "Start a container with at least a chosen share of capacity on a node of this type"
        default: true
        slug: small
        profile_options:
          image: &profile_options_image
            display_name: Image
            choices:
              python:
                display_name: Geospatial Python
                slug: python
                kubespawner_override:
                  image: openscapes/python:f577786
              iopython:
                display_name: Geospatial Python with tensorflow
                default: true
                slug: python
                kubespawner_override:
                  image: eeholmes/iopython:20230615
              rocker:
                display_name: Geospatial R
                slug: rocker
                kubespawner_override:
                  image: openscapes/rocker:a7596b5
              rocker:
                display_name: Geospatial R with SDM
                slug: rocker
                kubespawner_override:
                  image: eeholmes/iorocker:20230714
        kubespawner_override:
          cpu_limit: null
          mem_limit: null
          node_selector:
            node.kubernetes.io/instance-type: Standard_D8s_v3 
      - display_name: "Tiny: up to 2 CPU / 7 GB RAM"
        description: *profile_list_description
        slug: tiny
        profile_options:
          image: *profile_options_image
        kubespawner_override:
          cpu_limit: null
          mem_limit: null
          storage_capacity: null
          node_selector:
            node.kubernetes.io/instance-type: Standard_DS2_v2
dask-gateway:
  gateway:
    extraConfig:
      idle: |-
        # timeout after 30 minutes of inactivity
        c.KubeClusterConfig.idle_timeout = 1800 
```
