### ISSUE TITLE
dirsize-reporter OOMKilled and needs a larger memory request/limit - currently 16/128 MB

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2950]
In the `2i2c` cluster's `ohw` hub I saw that:

```
NAME                                           READY   STATUS    RESTARTS        AGE
shared-dirsize-metrics-654b445ddf-8lh76        1/1     Running   126 (99m ago)   32d
```

```yaml
    State:          Running
      Started:      Wed, 09 Aug 2023 14:56:07 +0200
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Wed, 09 Aug 2023 08:26:24 +0200
      Finished:     Wed, 09 Aug 2023 14:56:02 +0200
    Ready:          True
    Restart Count:  126
    Limits:
      cpu:     50m
      memory:  128Mi
    Requests:
      cpu:        10m
      memory:     16Mi
    Environment:  <none>
    Mounts:
      /shared-volume from shared-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2wwz7 (ro)
```
