### ISSUE TITLE
Figure out what that we mount in user pods that we must `chown` in an initContainer and why

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#2953]
We are currently using `chown` (change owner in a linux filesystem) on the mounted `/home/jovyan` and `/home/shared` folder (not on the files within, but the folder itself). I've always been a confused about the details to this, and hope that we could get to the bottom of this. If we do, we could perhaps use the knowledge to avoid redundant config and upstream improved docs in z2jh etc.

## Understanding goals

- To understand in detail when the `initContainer` doing a `chown` on the mounted directory is needed
  - Is it dependent on the NFS Server?
  - Is it dependent on the NFS mount options?
  - Is it dependent on the k8s version?
  - Is it dependent on mounting inside another NFS mount, like mounting /home/jovyan and then /home/jovyan/shared inside it?
    - If mounting for example shared inside /home/jovyan, how does an existing directory's permission influence the outcome?

## Related

- In #2946 I concluded that mounting the `shared` volume inside a mounted user's home directory, we end up creating a new directory in the mounted home directory.

## Practical goals

- Understand and document what goes on
- Cleanup our own config to not include uneccessary things
- Upstream docs improvements to z2jh

**Comment by consideRatio** [comment]
I digged into this and learned quite a bit.

## Conclusions

**The concludes are based on:**

- using the test pod below in GKE v1.26.x against a GCP Filestore, 2023-08-09
- using the NFS mount options "soft" and "noatime"
- only using volumeMounts with `subPath` specified as non-root directory
- creating folders and files at mount target paths with various owners
- changing owners after a container has started from various locations

**The conclusions are:**

- When mounting a subPath that doesn't exist, its created by root
- When nesting mounts, such as mounting B in A at path a/b, then:
  - If path b didn't already exist in A, then an empty folder b owned by root is created in A.
  - If path b existeded in A, then b is hidden and untouched in the container by B.
- The owner of a directory in NFS determines the owner of the directory in the container - during container startup.
- `chown` on a subPath mounted NFS directory impacts the ownership in NFS of the directory.

So this means that new directories for a new user for example to be chowned once, or alternatively pre-created with the right owner.

## A test pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-nfs
  namespace: staging
spec:
  volumes:
    - name: home
      persistentVolumeClaim:
        claimName: home-nfs

  securityContext:
    fsGroup: 100

  initContainers:
    - image: busybox
      name: volume-mount-ownership-fix
      securityContext:
        runAsUser: 0
      command:
        - sh
        - -c
        - chown 1000:1000 /home/new-directory-to-chown
      volumeMounts:
        - mountPath: /home/new-directory-to-chown
          subPath: "new-directory-to-chown"
          name: home

  containers:
    - image: jupyter/base-notebook:2023-06-19
      name: notebook
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1000
      volumeMounts:
        # Testing the following directory structure mounted
        #
        # - root-owned-1
        #   - root-owned-2
        #   - 1000-owned-2
        # - 1000-owned-1
        #   - root-owned-3
        #   - 1000-owned-3
        #
        # These are directories on the NFS volume referenced by subPath, where
        # they are owned by either 1000 or root.
        #
        #   ls -lh | grep owned
        #   drwxr-xr-x  2 1000 1000 4.0K Aug  9 17:42 1000-owned-1
        #   drwxr-xr-x  2 1000 1000 4.0K Aug  9 17:42 1000-owned-2
        #   drwxr-xr-x  2 1000 1000 4.0K Aug  9 17:42 1000-owned-3
        #   drwxr-xr-x  2 root root 4.0K Aug  9 17:42 root-owned-1
        #   drwxr-xr-x  2 root root 4.0K Aug  9 17:42 root-owned-2
        #   drwxr-xr-x  2 root root 4.0K Aug  9 17:42 root-owned-3
        #
        # Result in container:
        #
        #   ls -lh /home | grep owned
        #   drwxr-xr-x 4 jovyan  1000 4.0K Aug  9 17:47 1000-owned-1
        #   drwxr-xr-x 4 root   root  4.0K Aug  9 17:47 root-owned-1
        #
        #   ls -lh /home/root-owned-1 | grep owned
        #   drwxr-xr-x 2 jovyan 1000 4.0K Aug  9 17:42 1000-owned-2
        #   drwxr-xr-x 2 root   root 4.0K Aug  9 17:42 root-owned-2
        #
        #   ls -lh /home/1000-owned-1 | grep owned
        #   drwxr-xr-x 2 jovyan 1000 4.0K Aug  9 17:42 1000-owned-3
        #   drwxr-xr-x 2 root   root 4.0K Aug  9 17:42 root-owned-3
        #
        #   ls -lh /home | grep new-directory
        #   drwxr-xr-x 2 root   root  4.0K Aug  9 17:55 new-directory
        #   drwxr-xr-x 2 jovyan 1000 4.0K Aug  9 17:42 new-directory-to-chown
        #
        # Results in the NFS volume:
        #
        #   ls -lh 1000-owned-1
        #   drwxr-xr-x  2 root root 4.0K Aug  9 17:47 1000-owned-3
        #   drwxr-xr-x  2 root root 4.0K Aug  9 17:47 root-owned-3
        #
        #   ls -lh root-owned-1
        #   drwxr-xr-x  2 root root 4.0K Aug  9 17:47 1000-owned-2
        #   drwxr-xr-x  2 root root 4.0K Aug  9 17:47 root-owned-2
        #
        # root owns a dir, with two dirs mounted in it owned by root and 1000
        - mountPath: /home/root-owned-1
          subPath: root-owned-1
          name: home
        - mountPath: /home/root-owned-1/1000-owned-2
          subPath: 1000-owned-2
          name: home
        - mountPath: /home/root-owned-1/root-owned-2
          subPath: root-owned-2
          name: home
        # 1000 owns a dir, with two dirs mounted in it owned by root and 1000
        - mountPath: /home/1000-owned-1
          subPath: 1000-owned-1
          name: home
        - mountPath: /home/1000-owned-1/1000-owned-3
          subPath: 1000-owned-3
          name: home
        - mountPath: /home/1000-owned-1/root-owned-3
          subPath: root-owned-3
          name: home
        # mount a directory not previously defined
        - mountPath: /home/new-directory
          subPath: new-directory
          name: home
        # mount a directory not previously defined, and chown it in an initContainer
        - mountPath: /home/new-directory-to-chown
          subPath: new-directory-to-chown
          name: home

```
