### ISSUE TITLE
carbonplan: tune dask-gateway requested memory/cpu

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3417]
The work done by dask-gateway's traefik pod, controller pod, and gateway pod are low, so we can reduce these requests by a lot. Doing that will help reduce the cost for carbonplan's core nodes as they probably only will need one instead of two then.

```yaml
dask-gateway:
  traefik:
    resources:
      requests:
        cpu: 0.5
        memory: 512Mi
      limits:
        cpu: 2
        memory: 4Gi
  controller:
    resources:
      requests:
        cpu: 0.5
        memory: 512Mi
      limits:
        cpu: 2
        memory: 4Gi
  gateway:
    resources:
      requests:
        cpu: 0.5
        memory: 512Mi
      limits:
        cpu: 2
        memory: 4Gi
```
