### ISSUE TITLE
[Request deployment] HHMI Spyglass Ephemeral Hub

### ISSUE THREAD

**Issue by colliand** [2i2c-org/infrastructure#3643]
### The GitHub handle of the community representative

pending (@colliand for now)

### Hub important dates

- as soon as possible and certainly by 2024-01-31

The template below does not exactly apply. This is a request for a publicly accessible binder designed (initially) to render notebooks in the Spyglass repository: https://github.com/LorenFrankLab/spyglass 

Eventually, this hub will likely be used to serve repos generated by various other research groups affiliated with HHMI. The current focus is to deploy infrastructure to enable a "magic link" that interactively renders Spyglass tutorial content. 

### Hub Authentication Type

pending

### First Hub Administrators

- edeno

### [GitHub Auth only] How would you like to manage your users?

None

### [GitHub Teams Auth only] Profile restriction based on team membership

Profile should be set up to work for Spyglass.

Spyglass uses an adjacent database. This was briefly discussed in a call with @yuvipanda .

### Hub logo image URL

should use same image on hhmi.2i2c.cloud hub which is not rendering right now; 

![HHMI-vertical-signature-color](https://github.com/2i2c-org/infrastructure/assets/1879041/76419ba9-6d1a-41fe-b9b7-56fd89e0da40)

### Hub logo website URL

https://hhmi.org

### Hub user image GitHub repository

to work with Spyglass for now. build on the fly via binder/GESIS tooling?

### Hub user image tag and name

pending

### Extra features you would like to enable

- [ ] Dedicated Kubernetes cluster
- [ ] Scalable Dask Cluster

### (Optional) Preferred cloud provider

None

### (Optional) Preferred cloud region

as with hhmi.2i2c.cloud

### (Optional) Billing and Cloud account

None

### Tasks to deploy the hub

- [ ] 1. Deploy information filled in above
- [ ] 2. Engineer who will deploy the hub is assigned
- [ ] 3. If using GitHub Orgs/Teams Auth, Engineer is given Owner rights to the org to set this up.
- [ ] 4. Initial Hub deployment PR <link to PR>
- [ ] 5. Administrators able to log on -> Hub now in steady-state

**Comment by jmunroe** [comment]
There is overlap here with the request in 
- https://github.com/2i2c-org/infrastructure/issues/3624

The immediate priority is the for a binder-like or nbgitpuller-like URL to render the notebooks in the Spyglass repository https://github.com/LorenFrankLab/spyglass using the environment defined in https://github.com/LorenFrankLab/hhmi-spyglass-image  .  For the preprint, the LorenFrank group may also created a more tailored repository of just the notebooks and configuration files and not include the Spyglass source code .

This group is about publish a preprint that will include a URL that needs to redirect and unauthenticated user to an ephemeral (no permanent storage) JupyterHub that also supports an ephemeral MySQL database in a sidecar container.  @2i2c-org/engineering is request to provide guidance on how to achieve this behaviour.

HHMI represents several independent communities who will need to control their own environments. Rather than having those groups manage their own image environments, a GESIS-like binder build process could be deployed with persistent storage for authenticated users.

There is also value in having a more traditional BinderHub deployed for arbitrary code execution with no persistent storage. It is not clear to me if this needs to be unauthenticated users or could be wrapped behind some sort of light registration layer.

While the hub is discussing a 'HHMI Hub', i think it we may need to consider it more as a collection of hubs on the same HHMI cluster.

**Comment by yuvipanda** [comment]
There are two ways to approach this:

1. Set this up as an ephemeral hub (documented in https://infrastructure.2i2c.org/howto/features/ephemeral/) as @jmunroe suggests
2. Set this up instead as a binderhub, and use the allowed_repos feature of binderhub to restrict which one it can go to.

Given the timeline *and* the fact that we need to have some additional db (https://github.com/2i2c-org/infrastructure/issues/3624 sidecar), I think we should proceed with (1) (as documented in https://infrastructure.2i2c.org/howto/features/ephemeral/)).

I do think this ephemeral hub should be temporary, and we should switch it out to a binderhub soon. But this lets us do this piecemeal.

So tasks here are:

- [ ] Set up an ephemeral hub in the HHMI cluster (https://infrastructure.2i2c.org/howto/features/ephemeral/). Let's use CILogon but with `allow_all`. This is not blocked on me right now.
- [ ] Set up the mysql sidecar. I don't have any information on this - so this is currently blocked on @jmunroe.
- [ ] Set up an nbgitpuller link and decide what image this should be using. I don't know who is responsible for this. I think @jmunroe may have information here too?
- [ ]  Bring in all the work we have been doing on `cryptnono` and enable that here just for this cluster. More information in https://github.com/jupyterhub/mybinder.org-deploy/security/advisories/GHSA-j42g-x8qw-jjfh (but probably not visible to most users here?). This is blocked on me, and instead of actually doing the thing I will write documentation that describes how to do this.
- [ ] Determine who is the technical point of contact in the 2i2c side, and document that so we avoid confusion here - especially in the tight timelines that we have.

**Comment by jmunroe** [comment]
I agree that deploying an ephemeral hub in the HHMI cluster is a good initial step to solve the the needs of the Loren Frank group.  

There is already some configuration in `hhmi/common.values.yaml` that can be pulled out into this new ephemeral hub on the same cluster.

For the image:
```
image: "quay.io/lorenlab/hhmi-spyglass-image:c307f9418a60"
```

For the mysql sidecar :

```
    singleuser:
      extraContainers:
        - name: mysql
          image: datajoint/mysql # following the spyglass tutorial at https://lorenfranklab.github.io/spyglass/latest/notebooks/00_Setup/#existing-database
          ports:
            - name: mysql
              containerPort: 3306
          resources:
            limits:
              # Best effort only. No more than 1 CPU, and if mysql uses more than 4G, restart it
              memory: 4Gi
              cpu: 1.0
            requests:
              # If we don't set requests, k8s sets requests == limits!
              # So we set something tiny
              memory: 64Mi
              cpu: 0.01
          env:
            # Configured using the env vars documented in https://lorenfranklab.github.io/spyglass/latest/notebooks/00_Setup/#existing-database
            - name: MYSQL_ROOT_PASSWORD
              value: "tutorial"
```

And I really like the idea of using nbgitpuller link . The desire from HHMI is "magic-link" that will direct readers to a environment where the notebooks are available and can be run. The specific details of binder or nbgitpuller are not important HHMI.

I will work with the LorenFrank group to ensure the nbgitpuller link works as intended.
