### ISSUE TITLE
[Support] Increase RAM size on spyglass.hhmi.2i2c.cloud to 3.7GB

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#3670]
### Context

This request is from the #hhmi_pilot Slack channel and is related to 
- https://github.com/2i2c-org/infrastructure/issues/3624

### Proposal

I think I just need to add the following to `config/clusters/hhmi/spyglass.values.yaml`

```
kubespawner_override:
  mem_guarantee: 3644869120
  mem_limit: 3644869120
  cpu_guarantee: 0.434625
  cpu_limit: 3.477
  node_selector:
    node.kubernetes.io/instance-type: n2-highmem-4
```

### Updates and actions

I'll assign myself to complete this task.
