### ISSUE TITLE
Explore translating `latest` to a digest, and possibly then other tags, to improve reproducibility

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3707]
`latest` tags are practical but using them comes with a key compromise: you won't know what image version you ended up using. Maybe the `latest` tag at the time it was loaded the same as the tag `2024-02-07`, but you wouldn't know.

If we could get a user server understand how to reference the image started via a image digest, we may be able to improve reproducibility.

## Tech reading

- [Image digests](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#digests)

**Comment by consideRatio** [comment]
### Using kubectl to get digest of a container

When a container is started, its possible to detect from the k8s Pod's `containerStatuses` what image is referenced and what image was in the end used via a image digest:

```yaml
  # ...
  containerStatuses:
  - containerID: containerd://8c82914618e37233be782768182cb322877ea61a5f21c440467d1ff18ea3005e
    image: quay.io/jupyterhub/configurable-http-proxy:4.6.1
    imageID: quay.io/jupyterhub/configurable-http-proxy@sha256:fd916f75415f1e7e813c5a18b34a6042a601604938ff8777b044447efb3bd819
  # ...
```
