### ISSUE TITLE
[EVENT] Openscapes, large single day event, March 14th

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#3743]
### The link towards the Freshdesk ticket this event was reported

https://2i2c.freshdesk.com/a/tickets/1344

### The GitHub handle or name of the community representative

Brianna Lind, blind@contractor.usgs.gov

### The date when the event will start

March 14, 2024

### The date when the event will end

March 14, 2024

### What hours of the day will participants be active? (e.g., 5am - 5pm US/Pacific)

12:00pm PST (https://arewemeetingyet.com/Los%20Angeles/2024-03-14/12:00)

### Are we three weeks before the start date of the event?

- [X] Yes (it was when the ticket was opened, but not at the time I've transferred it to an issue)
- [ ] No

### Number of attendees

230, expecting 16GB usage each, maybe more

### Make sure to add the event into the calendar

- [ ] Done

### Does the hub already exist?

- [X] Yes
- [ ] No

### The URL of the hub that will be used for the event

https://openscapes.2i2c.cloud

### Will this hub be decommissioned after the event is over?

- [ ] Yes
- [X] No

### Was all the info filled in above?

- [ ] Yes
- [ ] No

### Quotas from the cloud provider are high-enough to handle expected usage?

- [ ] Yes
- [ ] No

**Comment by sgibson91** [comment]
From the freshdesk ticket:

> - Date: March 14, 2024
> - Time: 12:00 pm PST
> - Language: Python
> - No. participants: 230
> - Expected usage: 16 GB (per/participant)..... possibly slightly larger
> 
> Do you think there is anything specific that needs to be done in order to facilitate this? We'd also like to request that during the workshop, we can have files in the shared folder be read only on the hub.

**Comment by sgibson91** [comment]
Assignee can see if this guide is helpful: https://infrastructure.2i2c.org/howto/prepare-for-events/event-prep/#pre-warm-the-hub-to-reduce-wait-times

**Comment by consideRatio** [comment]
I'm not completing this or assigning myself, but note:

- Their resource allocation choices have requests == limits, making them not share ram - safe but expensive.
- The resource allocation choices provides the following choices, none of them map directly to "16 GB" or "slightly more".
  ```
                  mem_14_8:
                    display_name: 14.8 GB RAM, upto 3.7 CPUs
                    kubespawner_override:
                      mem_guarantee: 15941615616
                      mem_limit: 15941615616
                      cpu_guarantee: 1.875
                      cpu_limit: 3.75
                      node_selector:
                        node.kubernetes.io/instance-type: r5.xlarge
                  mem_29_7:
                    display_name: 29.7 GB RAM, upto 3.7 CPUs
                    kubespawner_override:
                      mem_guarantee: 31883231232
                      mem_limit: 31883231232
                      cpu_guarantee: 3.75
                      cpu_limit: 3.75
                      node_selector:
                        node.kubernetes.io/instance-type: r5.xlarge
  ```
- The r5.xlarge is a 4 CPU / 32 GB node, so if they show up with 230 users, it will be ~115 or ~230 nodes starting based on what is picked. This would be a terrible user experience, and could make us run into trouble with quotas etc as well!

---

I think its super relevant they are put on larger nodes to house a few tens of users at least. I think using ~64 CPU / 512GB nodes makes sense (`r5.16xlarge`), they would house ~32 users requesting ~16 GB then.

**Comment by sgibson91** [comment]
According to Openscapes' eksctl config, they already have an r5.16xlarge nodepool available, so I think this is just about exposing it via the profile list

https://github.com/2i2c-org/infrastructure/blob/c47a4363a40bce7703ab58bbbf75d5ec513d9950/eksctl/openscapes.jsonnet#L35

Doing a search for r5.16xlarge in the [common config file](https://github.com/2i2c-org/infrastructure/blob/master/config/clusters/openscapes/common.values.yaml) does not yield any results.

My plan for this event is therefore:

- Add a profile list option exposing the r5.16xlarge node type with appropriate resource requests
- Scale up the nodepool in the European morning on the day of the event (to at least one)
- Scale down the nodepool the day after the event
- Optionally, remove the profile list option. I will check with the hub champion.

**Comment by sgibson91** [comment]
Passing r5.16xlarge to the resource allocation script, and asking it to generate 10 examples, produces the following profile list options that jumps from 15GB to 30GB. So close!

```
mem_15_3:
  display_name: 15.3 GB RAM, upto 63.6 CPUs
  kubespawner_override:
    mem_guarantee: 16437845376
    mem_limit: 16437845376
    cpu_guarantee: 1.9875
    cpu_limit: 63.6
    node_selector:
      node.kubernetes.io/instance-type: r5.16xlarge
mem_30_6:
  display_name: 30.6 GB RAM, upto 63.6 CPUs
  kubespawner_override:
    mem_guarantee: 32875690752
    mem_limit: 32875690752
    cpu_guarantee: 3.975
    cpu_limit: 63.6
    node_selector:
      node.kubernetes.io/instance-type: r5.16xlarge
```

I think I need to adjust the strategy the script is using, but I don't know how to learn which options there are and what they do. There is not much info in either the help string or [documentation](https://infrastructure.2i2c.org/topic/resource-allocation/)

```
$ deployer generate resource-allocation choices --help
                                                                                                                                                                                    
 Usage: deployer generate resource-allocation choices [OPTIONS] INSTANCE_TYPE                                                                                                       
                                                                                                                                                                                    
 Generate a custom number of resource allocation choices for a certain instance type, depending on a certain chosen strategy.                                                       
                                                                                                                                                                                    
╭─ Arguments ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ *    instance_type      TEXT  Instance type to generate Resource Allocation options for [default: None] [required]                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --num-allocations        INTEGER                         Number of choices to generate [default: 5]                                                                              │
│ --strategy               [proportional-memory-strategy]  Strategy to use for generating resource allocation choices choices                                                      │
│                                                          [default: ResourceAllocationStrategies.PROPORTIONAL_MEMORY_STRATEGY]                                                    │
│ --help                                                   Show this message and exit.                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
