### ISSUE TITLE
Ensure our buckets are setup consistently for all hubs

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3864]
There are more buckets setup than we have misc other things setup.

For each hub with buckets setup via terraform, we should ensure the config aligns to make use of it. There are three things I know needs to be setup.

- environment variables
   ```yaml
     singleuser:
       extraEnv:
         SCRATCH_BUCKET: s3://scratch-go-bgc/$(JUPYTERHUB_USER)
   ```
   - [x] All AWS hubs (via #3977)
   - [ ] All GCP hubs
- k8s ServiceAccount cloud specific annotations to grant access
   Via `userServiceAccount.annotations`
   - [x] All AWS hubs (via #3977)
   - [ ] All GCP hubs
- singleuser.cloudMetadata.blockCloudMetadata
   ```yaml
     singleuser:
       cloudMetadata:
         blockWithIptables: false
   ```
   - [ ] All AWS hubs
   - [ ] All GCP hubs
