### ISSUE TITLE
Re-generate resource allocations for hubs in EKS clusters to work if upgraded to k8s 1.28

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#3902]
## DRAFT WRITEUP

Still working on writing this up

---

We've seen how the allocatable cpu and memory, combined with daemonset overhead, changed when using EKS 1.29 compared to EKS 1.28.

## Allocatable CPU change

This stems from `aws-node` now runs two containers instead of one, where each require 25m CPU.

```yaml
  openscapes:
    requesting_daemon_sets: aws-node,ebs-csi-node,kube-proxy,support-cryptnono,support-prometheus-node-exporter
    other_daemon_sets: ""
    cpu_requests: 170m
    memory_requests: 250Mi
    k8s_version: v1.27.10-eks-508b6b3
  opensci:
    requesting_daemon_sets: aws-node,ebs-csi-node,kube-proxy,support-cryptnono,support-prometheus-node-exporter
    other_daemon_sets: ""
    cpu_requests: 195m
    memory_requests: 250Mi
    k8s_version: v1.28.6-eks-508b6b3
```
