### ISSUE TITLE
[Support] catalystproject-latam, plnc: Add GPU profile (1 GPU + 4 GPU option)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4162]
### The Freshdesk ticket link

https://2i2c.freshdesk.com/a/tickets/1591

### Ticket request type

Feature Request

### Ticket impact

🟩 Low

### Short ticket description

We should enable the community to start servers with 1 and 4 GPUs respectively:

- n1-highmem-4 + 1 nvidia-tesla-T4 GPU (for small workloads)
- n2-highmem-16 + 4 nvidia-tesla-T4 GPUs (for large workloads)

### Related documentation

- https://infrastructure.2i2c.org/howto/features/gpu/

### Additional notes

Practically, I propose a dedicated profile_list entry for GPU, where the machine type + GPU count is determined by a option under the profile.

The image choices etc for this profile isn't specified by the community or me yet, so I propose a call is made and we ask for feedback.

Below are examples of how I think we need to declare kubespawner_override for the options choosing the hardware within the GPU profile

```yaml
          kubespawner_override:
            # also here should be cpu/memory requests/limit to fill up the node picked
            environment:
              NVIDIA_DRIVER_CAPABILITIES: compute,utility
            node_selector:
              node.kubernetes.io/instance-type: n1-highmem-4
            extra_resource_limits:
              nvidia.com/gpu: "1"

          # .....

          kubespawner_override:
            # also here should be cpu/memory requests/limit to fill up the node picked
            environment:
              NVIDIA_DRIVER_CAPABILITIES: compute,utility
            node_selector:
              node.kubernetes.io/instance-type: n1-highmem-16
            extra_resource_limits:
              nvidia.com/gpu: "4"
```
