### ISSUE TITLE
kubespawner does not support extra_tolerations

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/infrastructure#4245]
I was following https://infrastructure.2i2c.org/howto/features/dedicated-nodepool/#gcp to add new node pool for use in unam.latam.catalystproject.2i2c.cloud .

The instructions say to add

```
jupyterhub:
  singleuser:
    nodeSelector:
      2i2c.org/community: <community-name>
    extraTolerations:
      - key: 2i2c.org/community
        operator: Equal
        value: <community-name>
        effect: NoSchedule
```

but that hub uses a ProfileList.  I tried to add the `extra_tolerations` under a 'kubespawner_override` under the relevant section but it appears kubespawner does did not support the that toleration. As a temporary fix, I applied this extraTolerations to all profile options.
