### ISSUE TITLE
Correctly apply `chown` to `/shared` folders across hubs

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#440]
# Summary

I needed to add a volume mount hack for the ~/shared folder. I'm not fully confident about this in general though, but this is what I did.

This change can now be seen in https://github.com/2i2c-org/pilot-hubs/pull/436/commits/9c5e6ee373545a2a4565e36b1342d1e16d35dd7c but below is a summary.

### Before

```yaml
          singleuser:
          # ...
            initContainers:
              # Need to explicitly fix ownership here, since EFS doesn't do anonuid
              - name: volume-mount-ownership-fix
                image: busybox
                command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan && ls -lhd /home/jovyan"]
                securityContext:
                  runAsUser: 0
                volumeMounts:
                  - name: home
                    mountPath: /home/jovyan
                    subPath: "{username}"
```

### Current

```yaml
          singleuser:
          # ...
            initContainers:
              # Need to explicitly fix ownership here, since EFS doesn't do anonuid
              - name: volume-mount-ownership-fix
                image: busybox
                command: ["sh", "-c", "id && chown 1000:1000 /home/jovyan /home/jovyan/shared && ls -lhd /home/jovyan"]
                securityContext:
                  runAsUser: 0
                volumeMounts:
                  - name: home
                    mountPath: /home/jovyan
                    subPath: "{username}"

                  # Added along with the /home/jovyan/shared entry in the `chown` command
                  - name: home
                    mountPath: /home/jovyan/shared
                    subPath: _shared
```

### Action points
- [ ] Conclude if this is needed and wanted
- [ ] Do this for the other hubs with this kind of logic in place.

  Note that I copied carbonplan.cluster.yaml for jmte.cluster.yaml that I've currently not pushed to the repo.
