### ISSUE TITLE
Making JupyterLab RTC an opt-in feature

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#441]
# Summary

JupyterLab Real Time Collaboration (RTC) is very soon generally available in JupyterLab 3.1 (3.1.0a10 is out now). The access control is non-existent and you simply grant access to remote control your server as if it was you yourself at this point.

# User Stories

- As an end user, I want to click a button and share access to my server and get a Real Time Collaboration experience.
- As an end user, I want to understand the security implication of my choices.

# Acceptance criteria

This enhancement will require significant exploration work, so making decisions on what is an acceptable outcome is a key first step where these acceptance criteria then later can be updated with.

- A end to end workflow for a user is enabled
  - Example: user clicks share button, provides a link to another user who is granted access
- Security is considered:
  - The token granting access provides access to the entire server now and later I think. What is acceptable from a security stand point and how to we get there?

# Important information

With `jupyterlab==3.1.0a10` installed, the following startup configuration change will enable link sharing access.

```yaml
          singleuser:
            # cmd: I've experimented with these settings to get a JupyterLab RTC
            #      setup functioning. It currently is, but is this what makes
            #      sense to get it to function?
            #
            #      ref: https://github.com/jupyterlab-contrib/jupyterlab-link-share/issues/10#issuecomment-851899758
            #      ref: https://github.com/jupyterlab/jupyterlab/blob/1c8ff104a99e294265e6cf476dcb46279b0c3593/binder/jupyter_notebook_config.py#L39
            #
            #      Note the default in z2jh is jupyterhub-singleuser.
            cmd:
              - jupyterhub-singleuser
              - --LabApp.collaborative=True
              - --ServerApp.allow_remote_access=True
```

With [jupyterlab-contrib/jupyterlab-link-share](https://github.com/jupyterlab-contrib/jupyterlab-link-share) we get a button exposing a token in a link that can be shared. I've opened an issue about this not functioning properly yet with modern versions of JupyterHub etc to my knowledge though, see: https://github.com/jupyterlab-contrib/jupyterlab-link-share/issues/10

# Tasks to complete

- [ ] Discuss and decide on acceptance criterias
- [ ] Implementation steps...
