### ISSUE TITLE
Transition to EKS managed addons (Enables NetworkPolicy enforcement via aws CNI)

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#4660]
There is a banner in https://eksctl.io/, linking to [Cluster creation flexibility for networking add-ons](https://eksctl.io/usage/addons/#cluster-creation-flexibility-for-default-networking-addons):

![image](https://github.com/user-attachments/assets/727ec1fe-942d-479b-8fde-f23f296ab590)

I think we should act related to this, and transition from installing `aws-cni`, `kube-proxy`, and `coredns` as `eksctl` managed (but EKS self-managed) addons with dedicated upgrade commands etc, towards installing them as EKS managed addons as enabled by `eksctl` config.

## Motivation

This approach is the new approach, and the old approach is being phased out I think. The new approach is what we find docs about in AWS, and only through the new approach can we for example understand how to enable network policy enforcement for `aws-cni` plugin.

For example, consider this part from an eksctl config example in [AWS docs](https://aws.amazon.com/blogs/containers/amazon-vpc-cni-now-supports-kubernetes-network-policies/), this is referencing the new approach where `vpc-cni`, `coredns`, and `kube-proxy` is explicitly listed as EKS managed addons. This accepts `configurationValues` with `enableNetworkPolicy`, but something equivalent for the old `eksctl` self-installed `vpc-cni` addon doesn't allow itself to be configured like this making us unable to enable network policy enforcement.

```yaml
addons:
  - name: vpc-cni
    version: 1.14.0
    attachPolicyARNs: #optional
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy 
    configurationValues: |-
      enableNetworkPolicy: "true"
  - name: coredns
  - name: kube-proxy
```

## Definition of done

- Updated and eksctl applied existing cluster templates
- Updated upgrade docs about addons upgrades, we should transition from using addon-dedicated commands
- Updated new cluster templates
