### ISSUE TITLE
[devseed] Create a helm chart called `jupyterhub-home-nfs` (or similar)

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#4724]
To integrate the NFS quotas into 2i2c infrastructure, we need a helm chart that sets up the required resources via kubernetes. This issue tracks creating that helm chart.

For now, the chart should just handle setting up these resources on AWS, and should be enabled by config that looks like:

```yaml
jupyterhub-home-nfs:
  aws:
    enabled: true
    aws-key-one: foo
    aws-key-two: bar
```

Compatibility with GCP and Azure can be tackled in future work.

Also, the EBS volumes should be setup assuming that the cluster are single zone. Multi-zone support can be tackled later.

### Definition of Done

- [ ] A new helm chart containing the `jupyterhub-home-nfs` resources exists
