### ISSUE TITLE
Adjust configured dummy display_name now showing up in fancy profile hubs

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#5027]
It seems that while before fancy profiles didn't present certain info via the UI - it now does. That makes our config like below worth updating.

```yaml
    singleuser:
      profileList:
        - display_name: "Only Profile Available, this info is not shown in the UI"
```

![Image](https://github.com/user-attachments/assets/34c1b846-4e2d-4418-9a96-caf773fb203a)

## Definition of done

- We have set the display_name in these situations to something that makes sense given that its now being presented
