### ISSUE TITLE
Docs: update dask support page

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/infrastructure#5172]
Update the https://infrastructure.2i2c.org/howto/features/dask/ to capture the node selector setup needed, since they will be using their own per hub nodegroup

```
dask-gateway:
    gateway:
      backend:
        scheduler:
          extraPodConfig:
            nodeSelector:
              2i2c/hub-name: prod
        worker:
          extraPodConfig:
            nodeSelector:
              2i2c/hub-name: prod
```
