### ISSUE TITLE
Consider exposing grafana via `https://<hub domain>/services/grafana`

### ISSUE THREAD

**Issue by consideRatio** [2i2c-org/infrastructure#535]
Via this configuration, grafana can be exposed via a subpath under /services/grafana, where traffic is routed via JupyterHub's configurable proxy, which in turn exposes that path to the grafana service.

I've not looked into detail if this is already done or not or how we have it setup. I'm just dumping information into this issue at this point.

```yaml
jupyterhub:
  hub:
    # ref: https://jupyterhub.readthedocs.io/en/stable/reference/services.html#properties-of-a-service
    services:
      grafana:
        # This will make the CHP proxy let /services/grafana route to the
        # grafana service in the k8s namespace, which lets us make use of
        # JupyterHub's HTTPS setup without needing something like nginx-ingress
        # + cert-manager and additional ingress k8s resources.
        url: http://grafana
# Reference on the Grafana Helm chart's configuration options:
# https://github.com/helm/charts/blob/master/stable/grafana/values.yaml
grafana:
  # Reference on Grafana's configuration options:
  # http://docs.grafana.org/installation/configuration
  grafana.ini:
    server:
      domain: hub.neurohackademy.org
      # NOTE: Don't use %(protocol)s in root_url, but hardcode https. If not, it
      #       will when redirecting the user to external authentication set with
      #       a redirect back query parameter to use http instead of https,
      #       which will be wrong. This is because the TLS termination is done
      #       without Grafanas knowledge by the ingress controller. If we would
      #       specify protocol to be https, then it would want to do the TLS
      #       termination itself so that also would fail.
      root_url: 'https://%(domain)s/services/grafana'
      serve_from_sub_path: true
      enforce_domain: true
      enable_gzip: true
      router_logging: true
```

### Action points to take

1. Decide if there is action points to take.
