### ISSUE TITLE
CI/CD infrastructure for hubs that is automated, tested, and parallelized 

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/infrastructure#879]
_This is a pitch for a multi-sprint project - it uses a slightly different structure so that we can test out how it feels!_

### Problem statement

We have some basic hub deployment infrastructure set up. However this is missing a few important pieces of functionality:

- We cannot deploy hubs in parallel, which means that one hub can bottleneck all others, and that updating one hub means updating all other hubs
- Our testing infrastructure can be flaky, which makes it hard to distinguish a "true failure" from a "false failure"
- Our configuration lumps all hubs into a single config file, which makes it harder to find and refer to one hub's configuration.

### Proposed solution

We should improve our hub CI/CD infrastructure with a few specific focus areas:

- Hubs should be deployed in parallel with one another in CI (not the deployer)
- We should have automated testing infrastructure that will prevent hub deployment if it fails
- Configuration should be done via a GitHub repository, and deployment should be automatically triggered

Here's a rough idea of how this could work:

- Each cluster has a folder that contains configuration for each hub on the cluster
- Each hub gets its own configuration file, which is a valid and standalone Z2JH config.
  - Maybe there is another shared configuration file that each hub can draw from for common settings across hubs.
- Adding a new hub's configuration will trigger the deployment of a JupyterHub with that configuration on that cluster.
- We deploy staging hubs for each hub. We run some kind of test on the staging hub for common workflows, and if it fails then the production hub for that community does not deploy.
- We have a "source of truth" for the hubs that we're running that is easy to glance through, which provides important information needed to maintain them, as well as a rough status of each.

### Guidance for implementation

A few things that *must* exist in the final product:

- **Canary deployments**: Deploying a hub should be stopped if an automated test does not pass.

**Things to test for**

A few ideas to include in testing infrastructure:

- Unauthorized users cannot log in
- Authorized users can spin up an interactive server properly
- Run a notebook designed for the base environment top to bottom without errors
- Run a notebook designed for a Dask Hub environment top to bottom without errors

**No gos / out-of-scope**

- This should not become a deep dive into deploying Kubernetes on different cloud providers, unless we *really* think there's something crucial to solve there that would enable the deployment of hubs. Instead we should just assume there's a k8s cluster available and focus this on deploying hubs.

**Related issues**

These are related issues, and some (or all) may be in-scope to close as part of this project

- [ ] https://github.com/2i2c-org/infrastructure/issues/586

#### 2022-01-19

We had a team meeting today to agree on a few next steps for @sgibson91 and @consideRatio to tackle some of this. Here's a rough idea of what we'd like to get done:

- [x] @sgibson91 and @consideRatio (+ others if interested) schedule a time to speak and come up with a proposal for the configuration structure that we want.
  - Ask "what features are we hoping / planning to support with 2i2c?" "What configuration structure will allow us to support those features?"
- [x] Share the proposal with others and decide next steps
- [x] https://github.com/2i2c-org/infrastructure/issues/857
- [x] https://github.com/2i2c-org/infrastructure/issues/937
- [x] https://github.com/2i2c-org/infrastructure/issues/279
- [x] https://github.com/2i2c-org/infrastructure/issues/818

I believe that @sgibson91 is championing this with @consideRatio providing support and collaboration!

**Comment by sgibson91** [comment]
> We should have automated testing infrastructure that will prevent hub deployment if it fails

I think this needs some clarification. Currently, we run automated tests _after_ we have deployed an upgrade to a hub. So this statement could either mean:

- Chained deployments were staging is deployed first followed by production-level hubs. Failure to deploy to staging halts deployment to the productions hubs. OR
- Some other form of testing we run before the deployment step, e.g., validating the helm template

> **Canary deployments:** Deploying a hub should be stopped if an automated test does not pass.

Again, clarification here. This should probably say "deploying to production-level hubs is halted if deployment to staging hubs fail"

> Adding a new hub's configuration will trigger the deployment of a JupyterHub with that configuration on that cluster.

This already happens since the CI/CD runs the deployer and the deployer uses the `--install` flag to create a deployment if it doesn't already exist. But we often don't do it in practice because, if for some reason deployment fails, we can currently only see logs locally, not in CI/CD, as secrets can be leaked.

---

I think it would also be cool to add `test-this-pr` to this project to enable testing on staging hubs from a PR. This fleshes out the **canary deployments**.

---

I am very keen to champion this project :smile:

**Comment by consideRatio** [comment]
I'd like to be an assistant on this project!

This work requires changes to the _deployer configuration file schema_. I suggest two phases of this work.

1. __Phase 2: Refactoring of the deployer script's configuration file schema__
  1. Suggest what changes are required (@sgibson91 @choldgraf)
  2. Review, iterate, and agree on changes (@2i2c-org/tech-team)
  3. Implement refactoring changes (@sgibson91)
2. __Phase 2: Update CI system__
  - Add helm template validation (#279) (@consideRatio does it, @sgibson91 assists)
  - Optimize deployment ordering (#818) (@sgibson91 does it, @consideRatio assists)
3. __At any time__
  - I think #586 can be worked on at any time independently from the other tasks.

**Comment by choldgraf** [comment]
Related to #908

We had an incident where unauthorized users could access a hub because the hub's configuration did not have `allowed_users` set (thus, JupyterHub allowed *all* users).

We should add some kind of validation for certain configuration that we know needs to be set. Maybe this is part of #279 ?

**Comment by choldgraf** [comment]
### Update

In our latest team meeting it seemed like @sgibson91 and @consideRatio were interested in focusing their efforts on this work for their next major focus area. To begin with they were going to work on https://github.com/2i2c-org/infrastructure/issues/857, and this effort will likely create new ideas for what else needs to be done in the CI/CD.

@consideRatio and @sgibson91 - how do you feel about scoping this effort for two weeks, and then doing a re-assessment and adjusting our scope then?

**Comment by sgibson91** [comment]
I think let's see how far we get in a month and then decide if what's left is worth another cycle?

**Comment by choldgraf** [comment]
That sounds good to me - but let's define what work we want to accomplish in that month. Of all the improvements that we could make towards CI/CD, what is a reasonable subset to shoot for? We can adjust over time as we learn more, but we'll be more effective if we have a target to aim towards.

Can @sgibson91 and @consideRatio scope out what they think would be the most impactful and realistic given that time frame?

**Comment by sgibson91** [comment]
I think definitely:

- isolating each hub config (and the changes to the deployer that requires); and
- parallelising CI

**Comment by choldgraf** [comment]
### Next steps

- [ ] @sgibson91 and @consideRatio (+ others if interested) schedule a time to speak and come up with a proposal for the configuration structure that we want.
  - Ask "what features are we hoping / planning to support with 2i2c?" "What configuration structure will allow us to support those features?"
- [ ] Share the proposal with others and decide next steps

**Comment by sgibson91** [comment]
https://github.com/2i2c-org/infrastructure/issues/903 is a small fix that I think would be easily tackled as part of this project too

**Comment by sgibson91** [comment]
@2i2c-org/tech-team we have outlined a proposal for the refactor of the file structure here: https://hackmd.io/@29EjZnuAQx-ME7Olgi2JXw/Sk5S7xP6F

**Comment by damianavila** [comment]
I like the proposal!! Left a tiny comment but, from the top of my head, I do not see a blocker so I would be +1 on it.

**Comment by choldgraf** [comment]
I went through and left a few comments myself as well - in general I think it looks like a pretty clean and well-structured setup. A nice improvement!

**Comment by sgibson91** [comment]
Thanks for the comments so far! If there are no strong pushbacks in the next day or so, I'll begin implementing the batches of work outlined in the document.

**Comment by sgibson91** [comment]
I am going to start working on the following todos from the hackmd in order:

- [ ] Rename `hub-templates` folder to `helm-charts`
- [ ] Migrate the `hubs.*.template` key to be `hubs.*.helm_chart` in `*cluster.yaml`
- [ ] Relocate the support chart into the `helm-charts` folder
- [ ] Rename `/config/hubs` to `/config/clusters`
- [ ] Migrate the `support.config` key to `support.helm_chart_values_files` and separate out the helm chart values from the cluster configuration
- [ ] Refactor configuration structure
  -  Migrate the `hubs.*.config` key to be `hubs.*.helm_chart_values_files` and separate the helm chart values into individual files.
  - Let each cluster have it’s own folder under `/config/clusters` that contains all the helm chart values files for each deployment
  - Migrate each `*.cluster.yaml` file to be a `cluster.yaml` file under each cluster folder in `/config/cluster`
- [ ] Add a new function to the deployer that can generate:
  - A list of helm chart values files from a given cluster name and hub name
  - the reverse
- [ ] Update deployer validate function to run `helm template`

**Comment by sgibson91** [comment]
If anyone has opinions on https://github.com/2i2c-org/infrastructure/issues/965 while I'm poking around in the deployer, I'd love to hear

**Comment by sgibson91** [comment]
**Update from a quick Slack chat with Erik:** values files should be defined relative to the location of the `cluster.yaml` file, not the location of where the deployer is invoked from

**Comment by sgibson91** [comment]
Drafting in here: https://github.com/2i2c-org/infrastructure/pull/985

**Comment by sgibson91** [comment]
How to deal with these sections is going to cause a headache. We don't know ahead of time which files contain the placeholder, so I can't see a way around this other than reading in every file in the list until you find the placeholder.

https://github.com/2i2c-org/infrastructure/blob/701e4a78c46e55c90df453a56b2c25461ac20110/deployer/utils.py#L49-L106

**Comment by consideRatio** [comment]
I'm not sure about "staff placeholders" meaning, there is no docstring for this function :cry:. I think though, its templating configuration for various values to add/remove 2i2c staff to various lists? Maybe that should be done in logic as part of the jupyterhub startup routine as a hub.extraConfig entry (like a jupyterhub_config.py snippet) instead?

**Comment by sgibson91** [comment]
It is replacing this:

https://github.com/2i2c-org/infrastructure/blob/701e4a78c46e55c90df453a56b2c25461ac20110/config/clusters/pangeo-hubs.cluster.yaml#L78

with the list maintained here:

https://github.com/2i2c-org/infrastructure/blob/master/config/clusters/staff.yaml

**Comment by GeorgianaElena** [comment]
>@2i2c-org/teams/tech-team it would be great to have your input on a decision like this!

Dealing with the staff situation gave me lots of headaches too :( As someone who already tried various ways of implementing this and failed a few times from various reasons (https://github.com/2i2c-org/infrastructure/pull/311), I will dare to suggest to just go with the solution that makes life easier! The placeholder implementation was such type of solution too. So, whatever makes more sense with the new refactored structure.

The script suggestion sounds good :+1: (though I remember trying and failing to implement something similar because I didn't know how to determine which authentication method was chosen (google/github) from within the `hub.extraConfig` and also the `username_pattern` seemed hard to determine :disappointed:)

**Comment by consideRatio** [comment]
Any additional information for the script in `hub.extraConfig` can be passed via the `custom` section, preferably for example `custom.2i2c.<something>` as that would help clarify that this is 2i2c that has given this custom config meaning for anyone down the line to better comprehend what's related to what.

Here is a reduced example of what I'm thinking.

```yaml
custom:
  2i2c:
    addStaffUsersToAdminUsers: true
    staffUsers:
      - GeorgianaElena
      - sgibson91
      - consideratio
    # in practice, we need to have a list of different types of accounts and
    # some logic to know what to use, perhaps by inspecting the kind of
    # c.JupyterHub.authenticator_class has been configured or via
    # via explicit declaration in `custom.2i2c.staffUserListToUse` etc
hub:
  extraConfig:
    2i2c_addStaffUsersToAdminUsers: |
      # ...
      staff_users = get_config("custom.2i2c.staffUsers", [])
      add_staff_users_to_admin_users = get_config("custom.2i2c.addStaffUsersToAdminUsers", False)
      if add_staff_users_to_admin_users:
          c.JupyterHub.admin_users.extend(staff_users)
```

**Comment by consideRatio** [comment]
> Are you suggesting we add the staff list in basehub too?

Yes I suggest both the script (`hub.extraConfig...`) and the staff list (`custom.2i2c...`) is centralized still, for example via basehub default values or via a dedicated helm chart values file that the various charts reference as one `--values <file>` to pass as part of `helm upgrade` etc.

**Comment by GeorgianaElena** [comment]
> Any additional information for the script in hub.extraConfig can be passed via the custom section, preferably for example custom.2i2c.<something>

That's a good idea! However, I still don't see how we can determine the auth type from within the script, without duplicating/moving this info in the custom section.  https://github.com/2i2c-org/infrastructure/blob/701e4a78c46e55c90df453a56b2c25461ac20110/config/clusters/2i2c.cluster.yaml#L24 

It might be that I'm missing something though

**Comment by consideRatio** [comment]
You are probably right about it being hard to decide what kind of user identity should be used. The authenticator may be against auth0 no matter what, but still different usernames etc should be used.

Since that is a configuration that I understand to be on how the deployer script automatically setups things with auth0, I suggest not entangling it with the choice of user lists anyhow which may not relate to auth0.

Here is a config structure proposal and perhaps functional example to add to the basehub default values, but to be combined with each helm chart configuring their own dedicated values that include setting `custom.2i2c.add_staff_user_ids_to_admin_users` and `custom.2i2c.add_staff_user_ids_of_type`.

While they could rely on a default value in the basehub helm chart, I think it's better that they don't to increase comprehensibility.

```yaml
custom:
  2i2c:
    # Should staff user id's be injected to the admin_users
    # configuration of the JupyterHub's authenticator by our
    # custom jupyterhub_config.py snippet as declared in hub.extraConfig?
    add_staff_user_ids_to_admin_users: false
    add_staff_user_ids_of_type: ""
    staff_github_ids:
      - choldgraf
      - consideRatio
      - damianavila
      - GeorgianaElena
      - sgibson91
      - yuvipanda
    staff_google_ids:
      - choldgraf@2i2c.org
      - erik@2i2c.org
      - damianavila@2i2c.org
      - georgianaelena@2i2c.org
      - sgibson@2i2c.org
      - yuvipanda@2i2c.org
hub:
  extraConfig:
    2i2c_add_staff_user_ids_to_admin_users: |
      add_staff_user_ids_to_admin_users = get_config("custom.2i2c.add_staff_user_ids_to_admin_users", False)
      if add_staff_user_ids_to_admin_users:
          user_id_type = get_config(f"custom.2i2c.add_staff_user_ids_of_type")
          staff_user_ids = get_config(f"custom.2i2c.staff_{user_id_type}_ids", [])
          c.JupyterHub.admin_users.extend(staff_user_ids)
```

**Comment by choldgraf** [comment]
> I will dare to suggest to just go with the solution that makes life easier! The placeholder implementation was such type of solution too. So, whatever makes more sense with the new refactored structure.

I think that this is the right approach here. I can't speak to the specific proposal because I don't understand the deployer setup well enough, but I recall that in previous conversations, we were trying to balance "what works best for 2i2c" as well as "what makes it easy for others to replicate our setup from a R2R perspective".

At this point, I think it's more important that we make our lives easier and simpler. If it means there is some 2i2c special-casing in our deploying infrastructure, I think that's fine. I think it will be better to enable "Right to Replicate" by making sure the Z2JH / TLJH docs are good, and providing others some guidance in following them, rather than by choosing our own deployment setup so that it is copy/pasteable.

Not sure if this is a helpful comment or not, but thought I'd share in case this was a decision-factor

**Comment by consideRatio** [comment]
> Or are there things that @consideRatio would like to work on next week while Sarah is gone?

I have a full plate of work things to focus on already for at least two weeks. I'm not sure on the amount of work remaining to get those PRs merged, but I'd be happy to expedite review effort.

**Comment by sgibson91** [comment]
I think I should be able to have #988 ready for review/merge today and then can push as far as I can on #985. Theoretically, if there are no more blockers, it should be doable by the end of the week.

**Comment by sgibson91** [comment]
Ok, next blocker 😅 

[This function](https://github.com/2i2c-org/infrastructure/blob/fcd83405e42847b7b322d7d91b94e84a21c0d2b1/deployer/hub.py#L479) expects to be able to read the helm chart values in order to see if the `docs_service` is enabled and generate a token for it.

https://github.com/2i2c-org/infrastructure/blob/fcd83405e42847b7b322d7d91b94e84a21c0d2b1/deployer/hub.py#L504-L511

The `generated_config` never gets explicitly written to the helm chart values file. It is written to a temporary file and passed as another values file instead.

https://github.com/2i2c-org/infrastructure/blob/fcd83405e42847b7b322d7d91b94e84a21c0d2b1/deployer/hub.py#L564-L595

**Comment by consideRatio** [comment]
I think what I'd like most, would be if we broke the DRY principle. That would help demystify the deployer script which is too magic too me overall - doing things I don't keep track of it doing.

We have planned for something like...

```yaml
hubs:
  - name: staging
    domain: staging.us-central1-b.gcp.pangeo.io
    helm_chart: daskhub
    auth0:
      enabled: false
    helm_chart_values_files:
      - staging.values.yaml
```

What I'm thinking would help a lot with comprehensibility of what is done by the deployer script, and this situation, would be if we had like...

```yaml
hubs:
  - name: staging
    domain: staging.us-central1-b.gcp.pangeo.io
    helm_chart: daskhub
    auth0:
      enabled: false
    helm_chart_values_generated:
      docs_service_api_token: true
    helm_chart_values_files:
      - staging.values.yaml
```
