### ISSUE TITLE
Standardise our code formatting using automated tools in pre-commit, e.g., pyupgrade, black, flake8

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/infrastructure#938]
### Description of problem and opportunity to address it

**Context to understand the problem**

When working on code, I find it very beneficial to have a standardised format as I find it easier to quickly parse and understand the content. I think a standardised format also helps reviewing PRs as we can be sure the diffs presented are actual changes, not just stylistic choices. I also like the automate these kinds of formatting so that I can write code without worrying that I'm conforming to the style or not (thought I've found over the years, my natural writing style conforms more and more).

We already use [pre-commit](https://pre-commit.com/) to [auto-format our markdown and YAML files](https://github.com/2i2c-org/infrastructure/blob/master/.pre-commit-config.yaml), the latter being super important given that most of this repository is helm configuration.

I would like to propose adding [pyupgrade](https://github.com/asottile/pyupgrade), [black](https://black.readthedocs.io/en/stable/) and [flake8](https://flake8.pycqa.org/en/latest/) to our pre-commit config for autoformatting our Python files as well.

**Proposed solution**

I would like to add the below dependencies to our existing pre-commit config:

```yaml
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/psf/black
  rev: 21.12b0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ["--ignore=E501,W503"]
```

**What's the value and who would benefit**

I think this would allow us to maintain tidier code that is easier to work on as a team. Having it applied by pre-commit means that there's no additional overhead to engineers, they push their code as-is and pre-commit will format it.

@consideRatio and I would greatly benefit from implementing this standardised formatting before we take a deep dive into the deployer code as we work towards https://github.com/2i2c-org/infrastructure/issues/879 (and related issues).

We only have five open PRs at the minute and only one of them touches any Python files (and only two commented lines) so there will be a very small chance of introducing merge conflicts if we take this action soon.

### Updates and ongoing work

- [x] Gain approval from the team to implement this
- [x] https://github.com/2i2c-org/infrastructure/pull/939
- [ ] https://github.com/2i2c-org/team-compass/pull/357
